spring:
  application:
    name: service-a

server:
  port: 8080

rabbitmq:
  queue:
    a: a_queue
    c: c_queue
  exchange:
    a: a_exchange
  routingKey:
    a: a_routing_key

management:
  endpoint:
    health:
      group:
        liveness:
          include: ping, diskSpace
  probes:
    enabled: true
  tracing:
    sampling:
      probability: 1.0


logging:
  level:
    org.springframework.web: INFO

tracing:
  url: http://localhost:4317
